#!/usr/bin/env bun

/**
 * Install / remove the daily backup LaunchAgent (macOS).
 *
 * Replaces the committed `com.loewald.tosijs-backup.plist`, which hardcoded one
 * developer's home directory, project path and bun location, and claimed the
 * un-namespaced global label `com.loewald.tosijs-backup`. Since
 * `create-tosijs-platform-app` scaffolds by cloning this repo verbatim, that file
 * shipped to every downstream project: following its own INSTALL block gave you a
 * daily job cd-ing into a directory that does not exist, unable to write even the
 * error (launchd will not create a missing log parent), outliving the project that
 * installed it. (Review finding F18/F23.)
 *
 * Everything machine-specific is resolved HERE, at install time.
 *
 *   bun run backup:install     # write + load the agent
 *   bun run backup:uninstall   # unload + remove it
 *   bun run backup:install --dry-run
 */

import fs from 'fs'
import os from 'os'
import path from 'path'
import { execSync } from 'child_process'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, '..')
const args = process.argv.slice(2)
const has = (n) => args.includes(`--${n}`)
const uninstall = has('uninstall')
const dryRun = has('dry-run')

if (process.platform !== 'darwin') {
  console.error('This installer is macOS-only (launchd). On Linux use cron/systemd:')
  console.error(`  0 3 * * * cd ${projectRoot} && bun scripts/backup-firestore.js --quiet --keep 30`)
  process.exit(1)
}

function projectId() {
  try {
    return JSON.parse(
      fs.readFileSync(path.join(projectRoot, '.firebaserc'), 'utf-8')
    ).projects?.default
  } catch {
    return null
  }
}

const PROJECT_ID = projectId()
if (!PROJECT_ID) {
  console.error('Error: could not read project ID from .firebaserc')
  process.exit(1)
}

// Namespaced by project, so two projects on one machine do not fight over one
// label (launchctl load fails on a duplicate, silently leaving the first winner).
const LABEL = `com.tosijs-platform.backup.${PROJECT_ID}`
const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', `${LABEL}.plist`)
const logDir = path.join(os.homedir(), 'Backups', 'tosijs-platform', PROJECT_ID)
const logFile = path.join(logDir, 'backup.log')

if (uninstall) {
  if (!fs.existsSync(plistPath)) {
    console.log(`Nothing to remove — ${plistPath} does not exist.`)
    process.exit(0)
  }
  try {
    execSync(`launchctl unload ${JSON.stringify(plistPath)}`, { stdio: 'pipe' })
  } catch {
    // not loaded is fine
  }
  fs.unlinkSync(plistPath)
  console.log(`Removed ${LABEL}\n  ${plistPath}`)
  process.exit(0)
}

function which(cmd) {
  try {
    return execSync(`command -v ${cmd}`, { encoding: 'utf-8' }).trim()
  } catch {
    return null
  }
}

const bun = which('bun')
if (!bun) {
  console.error('Error: bun not found on PATH')
  process.exit(1)
}
if (!which('gcloud')) {
  console.error(
    'Warning: gcloud not found on PATH. The backup falls back to a gcloud access\n' +
      '  token when application default credentials are absent, so the scheduled run\n' +
      '  may fail. Check ' + logFile + ' after the first run.'
  )
}

// launchd jobs get no login shell, so PATH must be explicit and must include the
// directories bun and gcloud actually live in on THIS machine.
const pathEntries = [
  path.dirname(bun),
  '/opt/homebrew/bin',
  '/usr/local/bin',
  '/usr/bin',
  '/bin',
  '/usr/sbin',
  '/sbin',
]
const gcloud = which('gcloud')
if (gcloud) pathEntries.unshift(path.dirname(gcloud))
const PATH = [...new Set(pathEntries)].join(':')

const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by scripts/backup-install.js — do not commit or hand-edit.
  Project: ${PROJECT_ID}
  Regenerate: bun run backup:install
  Remove:     bun run backup:uninstall
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>-lc</string>
        <string>cd ${projectRoot} &amp;&amp; ${bun} scripts/backup-firestore.js --quiet --keep 30</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${PATH}</string>
    </dict>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key><integer>3</integer>
        <key>Minute</key><integer>0</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>${logFile}</string>
    <key>StandardErrorPath</key>
    <string>${logFile}</string>
</dict>
</plist>
`

if (dryRun) {
  console.log(`Would write ${plistPath}\n`)
  console.log(plist)
  process.exit(0)
}

// F23: launchd does not create intermediate directories, so without this the
// FIRST run's output — including the credential error the docs tell you to look
// for — is discarded, and the job appears to do nothing for no visible reason.
fs.mkdirSync(logDir, { recursive: true, mode: 0o700 })

// Refuse to clobber an agent installed from a DIFFERENT checkout: same project id
// from two working copies would otherwise silently repoint the schedule.
if (fs.existsSync(plistPath)) {
  const existing = fs.readFileSync(plistPath, 'utf-8')
  const m = existing.match(/<string>cd ([^ ]+) /)
  if (m && m[1] !== projectRoot) {
    console.error(
      `Error: ${LABEL} is already installed pointing at a different checkout:\n` +
        `  existing: ${m[1]}\n  this one: ${projectRoot}\n` +
        '  Run backup:uninstall there first, or pick a different Firebase project.'
    )
    process.exit(1)
  }
  try {
    execSync(`launchctl unload ${JSON.stringify(plistPath)}`, { stdio: 'pipe' })
  } catch {
    /* not loaded */
  }
}

fs.mkdirSync(path.dirname(plistPath), { recursive: true })
fs.writeFileSync(plistPath, plist)
execSync(`launchctl load ${JSON.stringify(plistPath)}`, { stdio: 'inherit' })

console.log(`Installed ${LABEL}
  plist:   ${plistPath}
  project: ${projectRoot}
  runs:    daily at 03:00, keeping 30 snapshots
  log:     ${logFile}

  check:     launchctl list | grep ${LABEL}
  run now:   launchctl start ${LABEL}
  remove:    bun run backup:uninstall

launchd will not tell you if a run fails — check the log occasionally.`)
